In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv('BX-Books.csv', sep=';', error_bad_lines=False, encoding='latin-1')

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
C:\Users\Chacha Tech\anaconda3\lib\site-packages\IPython\core\interactives

In [3]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [4]:
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [5]:
books.rename(columns={'Book-Title':'title', 'Book-Author':'author', 'Year-Of-Publication':'year', 'Publisher':'publisher'}, inplace=True)

In [6]:
books.head(2)

ISBN                title                author  year  \
0  0195153448  Classical Mythology    Mark P. O. Morford  2002   
1  0002005018         Clara Callan  Richard Bruce Wright  2001   

                 publisher  
0  Oxford University Press  
1    HarperFlamingo Canada

In [7]:
users = pd.read_csv('BX-Users.csv', sep=';', error_bad_lines=False, encoding='latin-1')

In [8]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [9]:
users.rename(columns={'User-ID':'user_id', 'Location':'location', 'Age':'age'}, inplace=True)

In [10]:
users.head()

user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [11]:
ratings = pd.read_csv('BX-Book-Ratings.csv', sep=';', error_bad_lines=False, encoding='latin-1')

In [12]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [13]:
ratings.rename(columns={'User-ID':'user_id',  'Book-Rating':'rating'}, inplace=True)

In [14]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 5)
(278858, 3)
(1149780, 3)


In [15]:
ratings.head(2)

user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5

In [16]:
ratings['user_id'].value_counts().shape

(105283,)

In [17]:
x=ratings['user_id'].value_counts()>200

In [18]:
x[x]

11676     True
198711    True
153662    True
98391     True
35859     True
          ... 
28634     True
188951    True
9856      True
268622    True
274808    True
Name: user_id, Length: 899, dtype: bool

In [19]:
x[x].shape

(899,)

In [20]:
y=x[x].index
y

Int64Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352,
            110973, 235105,
            ...
            260183, 155916,  44296,  73681,  59727,  28634, 188951,   9856,
            268622, 274808],
           dtype='int64', length=899)

In [21]:
ratings = ratings[ratings['user_id'].isin(y)]
ratings.shape

(526356, 3)

In [22]:
ratings.head()

user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [23]:
ratings_with_books = ratings.merge(books, on='ISBN')

In [24]:
ratings_with_books.head()

user_id        ISBN  rating  \
0   277427  002542730X      10   
1     3363  002542730X       0   
2    11676  002542730X       6   
3    12538  002542730X      10   
4    13552  002542730X       0   

                                               title             author  year  \
0  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
1  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
2  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
3  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   
4  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  1994   

                   publisher  
0  John Wiley &amp; Sons Inc  
1  John Wiley &amp; Sons Inc  
2  John Wiley &amp; Sons Inc  
3  John Wiley &amp; Sons Inc  
4  John Wiley &amp; Sons Inc

In [25]:
ratings_with_books.shape

(487671, 7)

In [26]:
num_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()

In [27]:
num_rating.rename(columns={'rating':'number_rating'}, inplace=True)

In [28]:
num_rating.head()

title  number_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [29]:
final_rating = ratings_with_books.merge(num_rating, on='title')

In [30]:
final_rating.shape

(487671, 8)

In [31]:
final_rating = final_rating[final_rating['number_rating']>=50]

In [32]:
final_rating.shape

(61853, 8)

In [33]:
final_rating.drop_duplicates(['user_id', 'title'], inplace=True)

In [34]:
final_rating.shape

(59850, 8)

In [35]:
book_pivot = final_rating.pivot_table(columns='user_id', index='title', values='rating')

In [36]:
book_pivot.head()

user_id                254     2276    2766    2977    3363    3757    4017    \
title                                                                           
1984                      9.0     NaN     NaN     NaN     NaN     NaN     NaN   
1st to Die: A Novel       NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2nd Chance                NaN    10.0     NaN     NaN     NaN     NaN     NaN   
4 Blondes                 NaN     NaN     NaN     NaN     NaN     NaN     NaN   
84 Charing Cross Road     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

user_id                4385    6242    6251    ...  274004  274061  274301  \
title                                          ...                           
1984                      NaN     NaN     NaN  ...     NaN     NaN     NaN   
1st to Die: A Novel       NaN     NaN     NaN  ...     NaN     NaN     NaN   
2nd Chance                NaN     NaN     NaN  ...     NaN     NaN     NaN   
4 Blondes                 NaN     NaN     0.0  ...     NaN     NaN     NaN   
84 Charing Cross Road     NaN     NaN     NaN  ...     NaN     NaN     NaN   

user_id                274308  274808  275970  277427  277478  277639  278418  
title                                                                          
1984                      NaN     NaN     0.0     NaN     NaN     NaN     NaN  
1st to Die: A Novel       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
2nd Chance                0.0     NaN     NaN     NaN     NaN     0.0     NaN  
4 Blondes                 NaN     NaN     NaN     NaN     NaN     NaN     NaN  
84 Charing Cross Road     NaN     NaN    10.0     NaN     NaN     NaN     NaN  

[5 rows x 888 columns]

In [37]:
book_pivot.shape

(742, 888)

In [38]:
book_pivot.fillna(0, inplace=True)

In [39]:
book_pivot.head()

user_id                254     2276    2766    2977    3363    3757    4017    \
title                                                                           
1984                      9.0     0.0     0.0     0.0     0.0     0.0     0.0   
1st to Die: A Novel       0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2nd Chance                0.0    10.0     0.0     0.0     0.0     0.0     0.0   
4 Blondes                 0.0     0.0     0.0     0.0     0.0     0.0     0.0   
84 Charing Cross Road     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

user_id                4385    6242    6251    ...  274004  274061  274301  \
title                                          ...                           
1984                      0.0     0.0     0.0  ...     0.0     0.0     0.0   
1st to Die: A Novel       0.0     0.0     0.0  ...     0.0     0.0     0.0   
2nd Chance                0.0     0.0     0.0  ...     0.0     0.0     0.0   
4 Blondes                 0.0     0.0     0.0  ...     0.0     0.0     0.0   
84 Charing Cross Road     0.0     0.0     0.0  ...     0.0     0.0     0.0   

user_id                274308  274808  275970  277427  277478  277639  278418  
title                                                                          
1984                      0.0     0.0     0.0     0.0     0.0     0.0     0.0  
1st to Die: A Novel       0.0     0.0     0.0     0.0     0.0     0.0     0.0  
2nd Chance                0.0     0.0     0.0     0.0     0.0     0.0     0.0  
4 Blondes                 0.0     0.0     0.0     0.0     0.0     0.0     0.0  
84 Charing Cross Road     0.0     0.0    10.0     0.0     0.0     0.0     0.0  

[5 rows x 888 columns]

In [40]:
# use scientific python library and import csr_matrix for handling lots of zeros in datasets.
from scipy.sparse import csr_matrix

In [41]:
book_sparse = csr_matrix(book_pivot) # only consisder non zeros for clustering.

In [42]:
type(book_sparse)

scipy.sparse.csr.csr_matrix

In [43]:
from sklearn.neighbors import NearestNeighbors

In [44]:
model = NearestNeighbors(algorithm='brute') # brute mean sub ka sub se comparison phir answer dy.

In [45]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [46]:
distances, suggestions = model.kneighbors(book_pivot.iloc[393,:].values.reshape(1, -1), n_neighbors = 6)

In [47]:
distances

array([[ 0.        , 19.        , 20.37154879, 20.66397832, 21.04756518,
        21.1896201 ]])

In [48]:
suggestions

array([[393, 372, 320, 184, 296,  35]], dtype=int64)

In [49]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Pleading Guilty', 'No Safe Place', 'Long After Midnight', 'Exclusive',
       'Journey', 'Absolute Power'],
      dtype='object', name='title')


In [50]:
book_pivot.index[393]

'Pleading Guilty'

In [51]:
book_pivot.index=='Pleading Guilty'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [52]:
np.where(book_pivot.index=='Pleading Guilty')

(array([393], dtype=int64),)

In [53]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index==book_name)[0][0]
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1, -1), n_neighbors = 6)
    
    for i in range(len(suggestions)):
         print(book_pivot.index[suggestions[i]])

In [54]:
recommend_book('Animal Farm')

Index(['Animal Farm', 'Exclusive', 'Jacob Have I Loved', 'Second Nature',
       'Pleading Guilty', 'No Safe Place'],
      dtype='object', name='title')
